using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DXFLib.DXF
{
    class hwpDxf_ConstNameDxf
	{
	public const string pcstrDxfObject = "OBJECT";

		public const string pcstrDxfFontTable = "FONTTABLE";

		public const string pcstrDxfFontTableRecord = "FONTTABLERECORD";

		public const string pcstrDxfVXTable = "VXTABLE";

		public const string pcstrDxfVXTableRecord = "VXTABLERECORD";

		public const string pcstrDxfSymbolTable = "TABLE";

		public const string pcstrDxfSymbolTableRecord = "TABLE_RECORD";

		public const string pcstrDxfBlockTable = "BLOCK_RECORD";

		public const string pcstrDxfDimStyleTable = "DIMSTYLE";

		public const string pcstrDxfLayerTable = "LAYER";

		public const string pcstrDxfLinetypeTable = "LTYPE";

		public const string pcstrDxfRegisteredApplicationTable = "APPID";

		public const string pcstrDxfTextStyleTable = "STYLE";

		public const string pcstrDxfUCSTable = "UCS";

		public const string pcstrDxfAbstractViewTable = "ABSTRACTVIEW";

		public const string pcstrDxfViewTable = "VIEW";

		public const string pcstrDxfViewportTable = "VPORT";

		public const string pcstrDxfEntity = "ENTITY";

		public const string pcstrDxfPlotSettings = "PLOTSETTINGS";

		public const string pcstrDxfProxyObject = "PROXYOBJECT";

		public const string pcstrDxfBlockBegin = "BLOCKBEGIN";

		public const string pcstrDxfBlockEnd = "BLOCKEND";

		public const string pcstrDxf3DFace = "3DFACE";

		public const string pcstrDxfPolyline = "POLYLINE";

		public const string pcstrDxf3DSolid = "3DSOLID";

		public const string pcstrDxfHatch = "HATCH";

		public const string pcstrDxfMLine = "MLINE";

		public const string pcstrDxfMText = "MTEXT";

		public const string pcstrDxfPoint = "POINT";

		public const string pcstrDxfShape = "SHAPE";

		public const string pcstrDxfSolid = "SOLID";

		public const string pcstrDxfTrace = "TRACE";

		public const string pcstrDxfCurve = "CURVE";

		public const string pcstrDxfArc = "ARC";

		public const string pcstrDxfCircle = "CIRCLE";

		public const string pcstrDxfEllipse = "ELLIPSE";

		public const string pcstrDxfLeader = "LEADER";

		public const string pcstrDxfLine = "LINE";

		public const string pcstrDxfRay = "RAY";

		public const string pcstrDxfSpline = "SPLINE";

		public const string pcstrDxfXline = "XLINE";

		public const string pcstrDxfLWPolyline = "LWPOLYLINE";

		public const string pcstrDxfVertex = "VERTEX";

		public const string pcstrDxfUnknownEnt = "UNBEKANNT";

		public const string pcstrDxfText = "TEXT";

		public const string pcstrDxfInsert = "INSERT";

		public const string pcstrDxfAttDef = "ATTDEF";

		public const string pcstrDxfSeqend = "SEQEND";

		public const string pcstrDxfAttrib = "ATTRIB";

		public const string pcstrDxfDictionary = "DICTIONARY";

		public const string pcstrDxfDictionaryWithDefault = "ACDBDICTIONARYWDFLT";

		public const string pcstrDxfGroup = "GROUP";

		public const string pcstrDxfMaterial = "MATERIAL";

		public const string pcstrDxfMLineStyle = "MLINESTYLE";

		public const string pcstrDxfPlotConfiguration = "PLOTCONFIGURATION";

		public const string pcstrDxfLayout = "LAYOUT";

		public const string pcstrDxfAcDbPlaceholder = "ACDBPLACEHOLDER";

		public const string pcstrDxfDictionaryVar = "DICTIONARYVAR";

		public const string pcstrDxfDictionaryEntry = "DICTIONARYENTRY";

		public const string pcstrDxfDictGroup = "ACAD_GROUP";

		public const string pcstrDxfDictMaterial = "ACAD_MATERIAL";

		public const string pcstrDxfDictPlotStyleName = "ACAD_PLOTSTYLENAME";

		public const string pcstrDxfDictMLineStyle = "ACAD_MLINESTYLE";

		public const string pcstrDxfDictPlotSettings = "ACAD_PLOTSETTINGS";

		public const string pcstrDxfDictLayout = "ACAD_LAYOUT";
	}

}

